name: Deploy Branches to Netlify

on:
  push:
    branches:
      - '*'  # Deploy every branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          site-id: ${{ secrets.NETLIFY_SITE_ID }}  # Optional if using manual site setup
          deploy-message: "Branch Deployment from GitHub Actions 🚀"
          alias: ${{ github.ref_name }}  # Each branch gets its own unique URL
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}  # Move token here
